/*Generated by WaveMaker Studio*/
package com.wmtheme.services.countryinfoservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-28T11:16:33.888Z
 * Generated source version: 3.2.7
 *
 */
public final class CountryInfoServiceSoapType_CountryInfoServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.oorsprong.org/websamples.countryinfo", "CountryInfoService");

    private CountryInfoServiceSoapType_CountryInfoServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CountryInfoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CountryInfoService ss = new CountryInfoService(wsdlURL, SERVICE_NAME);
        CountryInfoServiceSoapType port = ss.getCountryInfoServiceSoap12();

        {
        System.out.println("Invoking fullCountryInfo...");
        com.wmtheme.services.countryinfoservice.FullCountryInfo _fullCountryInfo_parameters = null;
        com.wmtheme.services.countryinfoservice.FullCountryInfoResponse _fullCountryInfo__return = port.fullCountryInfo(_fullCountryInfo_parameters);
        System.out.println("fullCountryInfo.result=" + _fullCountryInfo__return);


        }
        {
        System.out.println("Invoking countryFlag...");
        com.wmtheme.services.countryinfoservice.CountryFlag _countryFlag_parameters = null;
        com.wmtheme.services.countryinfoservice.CountryFlagResponse _countryFlag__return = port.countryFlag(_countryFlag_parameters);
        System.out.println("countryFlag.result=" + _countryFlag__return);


        }
        {
        System.out.println("Invoking countryName...");
        com.wmtheme.services.countryinfoservice.CountryName _countryName_parameters = null;
        com.wmtheme.services.countryinfoservice.CountryNameResponse _countryName__return = port.countryName(_countryName_parameters);
        System.out.println("countryName.result=" + _countryName__return);


        }
        {
        System.out.println("Invoking countryCurrency...");
        com.wmtheme.services.countryinfoservice.CountryCurrency _countryCurrency_parameters = null;
        com.wmtheme.services.countryinfoservice.CountryCurrencyResponse _countryCurrency__return = port.countryCurrency(_countryCurrency_parameters);
        System.out.println("countryCurrency.result=" + _countryCurrency__return);


        }
        {
        System.out.println("Invoking listOfCountryNamesByCode...");
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesByCode _listOfCountryNamesByCode_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesByCodeResponse _listOfCountryNamesByCode__return = port.listOfCountryNamesByCode(_listOfCountryNamesByCode_parameters);
        System.out.println("listOfCountryNamesByCode.result=" + _listOfCountryNamesByCode__return);


        }
        {
        System.out.println("Invoking listOfCurrenciesByName...");
        com.wmtheme.services.countryinfoservice.ListOfCurrenciesByName _listOfCurrenciesByName_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfCurrenciesByNameResponse _listOfCurrenciesByName__return = port.listOfCurrenciesByName(_listOfCurrenciesByName_parameters);
        System.out.println("listOfCurrenciesByName.result=" + _listOfCurrenciesByName__return);


        }
        {
        System.out.println("Invoking countryIntPhoneCode...");
        com.wmtheme.services.countryinfoservice.CountryIntPhoneCode _countryIntPhoneCode_parameters = null;
        com.wmtheme.services.countryinfoservice.CountryIntPhoneCodeResponse _countryIntPhoneCode__return = port.countryIntPhoneCode(_countryIntPhoneCode_parameters);
        System.out.println("countryIntPhoneCode.result=" + _countryIntPhoneCode__return);


        }
        {
        System.out.println("Invoking currencyName...");
        com.wmtheme.services.countryinfoservice.CurrencyName _currencyName_parameters = null;
        com.wmtheme.services.countryinfoservice.CurrencyNameResponse _currencyName__return = port.currencyName(_currencyName_parameters);
        System.out.println("currencyName.result=" + _currencyName__return);


        }
        {
        System.out.println("Invoking listOfCurrenciesByCode...");
        com.wmtheme.services.countryinfoservice.ListOfCurrenciesByCode _listOfCurrenciesByCode_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfCurrenciesByCodeResponse _listOfCurrenciesByCode__return = port.listOfCurrenciesByCode(_listOfCurrenciesByCode_parameters);
        System.out.println("listOfCurrenciesByCode.result=" + _listOfCurrenciesByCode__return);


        }
        {
        System.out.println("Invoking listOfLanguagesByCode...");
        com.wmtheme.services.countryinfoservice.ListOfLanguagesByCode _listOfLanguagesByCode_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfLanguagesByCodeResponse _listOfLanguagesByCode__return = port.listOfLanguagesByCode(_listOfLanguagesByCode_parameters);
        System.out.println("listOfLanguagesByCode.result=" + _listOfLanguagesByCode__return);


        }
        {
        System.out.println("Invoking languageISOCode...");
        com.wmtheme.services.countryinfoservice.LanguageISOCode _languageISOCode_parameters = null;
        com.wmtheme.services.countryinfoservice.LanguageISOCodeResponse _languageISOCode__return = port.languageISOCode(_languageISOCode_parameters);
        System.out.println("languageISOCode.result=" + _languageISOCode__return);


        }
        {
        System.out.println("Invoking capitalCity...");
        com.wmtheme.services.countryinfoservice.CapitalCity _capitalCity_parameters = null;
        com.wmtheme.services.countryinfoservice.CapitalCityResponse _capitalCity__return = port.capitalCity(_capitalCity_parameters);
        System.out.println("capitalCity.result=" + _capitalCity__return);


        }
        {
        System.out.println("Invoking listOfLanguagesByName...");
        com.wmtheme.services.countryinfoservice.ListOfLanguagesByName _listOfLanguagesByName_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfLanguagesByNameResponse _listOfLanguagesByName__return = port.listOfLanguagesByName(_listOfLanguagesByName_parameters);
        System.out.println("listOfLanguagesByName.result=" + _listOfLanguagesByName__return);


        }
        {
        System.out.println("Invoking listOfCountryNamesGroupedByContinent...");
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesGroupedByContinent _listOfCountryNamesGroupedByContinent_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesGroupedByContinentResponse _listOfCountryNamesGroupedByContinent__return = port.listOfCountryNamesGroupedByContinent(_listOfCountryNamesGroupedByContinent_parameters);
        System.out.println("listOfCountryNamesGroupedByContinent.result=" + _listOfCountryNamesGroupedByContinent__return);


        }
        {
        System.out.println("Invoking listOfCountryNamesByName...");
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesByName _listOfCountryNamesByName_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfCountryNamesByNameResponse _listOfCountryNamesByName__return = port.listOfCountryNamesByName(_listOfCountryNamesByName_parameters);
        System.out.println("listOfCountryNamesByName.result=" + _listOfCountryNamesByName__return);


        }
        {
        System.out.println("Invoking listOfContinentsByName...");
        com.wmtheme.services.countryinfoservice.ListOfContinentsByName _listOfContinentsByName_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfContinentsByNameResponse _listOfContinentsByName__return = port.listOfContinentsByName(_listOfContinentsByName_parameters);
        System.out.println("listOfContinentsByName.result=" + _listOfContinentsByName__return);


        }
        {
        System.out.println("Invoking languageName...");
        com.wmtheme.services.countryinfoservice.LanguageName _languageName_parameters = null;
        com.wmtheme.services.countryinfoservice.LanguageNameResponse _languageName__return = port.languageName(_languageName_parameters);
        System.out.println("languageName.result=" + _languageName__return);


        }
        {
        System.out.println("Invoking listOfContinentsByCode...");
        com.wmtheme.services.countryinfoservice.ListOfContinentsByCode _listOfContinentsByCode_parameters = null;
        com.wmtheme.services.countryinfoservice.ListOfContinentsByCodeResponse _listOfContinentsByCode__return = port.listOfContinentsByCode(_listOfContinentsByCode_parameters);
        System.out.println("listOfContinentsByCode.result=" + _listOfContinentsByCode__return);


        }
        {
        System.out.println("Invoking countriesUsingCurrency...");
        com.wmtheme.services.countryinfoservice.CountriesUsingCurrency _countriesUsingCurrency_parameters = null;
        com.wmtheme.services.countryinfoservice.CountriesUsingCurrencyResponse _countriesUsingCurrency__return = port.countriesUsingCurrency(_countriesUsingCurrency_parameters);
        System.out.println("countriesUsingCurrency.result=" + _countriesUsingCurrency__return);


        }
        {
        System.out.println("Invoking countryISOCode...");
        com.wmtheme.services.countryinfoservice.CountryISOCode _countryISOCode_parameters = null;
        com.wmtheme.services.countryinfoservice.CountryISOCodeResponse _countryISOCode__return = port.countryISOCode(_countryISOCode_parameters);
        System.out.println("countryISOCode.result=" + _countryISOCode__return);


        }
        {
        System.out.println("Invoking fullCountryInfoAllCountries...");
        com.wmtheme.services.countryinfoservice.FullCountryInfoAllCountries _fullCountryInfoAllCountries_parameters = null;
        com.wmtheme.services.countryinfoservice.FullCountryInfoAllCountriesResponse _fullCountryInfoAllCountries__return = port.fullCountryInfoAllCountries(_fullCountryInfoAllCountries_parameters);
        System.out.println("fullCountryInfoAllCountries.result=" + _fullCountryInfoAllCountries__return);


        }

        System.exit(0);
    }

}